### ISSUE TITLE
Nested lines don't work in xbar

### ISSUE THREAD

**Issue by onaront** [matryer/xbar#648]
Example:
```
#!/bin/bash
echo "a"
echo "---"
echo "b"
echo "--c"
echo "-----"
echo "--d"
```
This shows nested line in BitBar but not xbar

**Comment by matryer** [comment]
@onaront thanks for reporting this - please try the [latest release](https://github.com/matryer/xbar/releases/latest), I think I fixed it.

**Comment by onaront** [comment]
Looks fixed now, thanks.

**Comment by onaront** [comment]
Actually there's still a problem. Try this:
```
#!/bin/bash
echo "a"
echo "---"
echo "--c"
echo "-----"
echo "--d"
echo "---"
echo "f"
```
Last line does not show, but it shows as single dash in the sub menu.

**Comment by matryer** [comment]
Hey @onaront - please give the [latest release](https://github.com/matryer/xbar/releases/latest) a try.

**Comment by onaront** [comment]
Looks like it's working. Thanks!
